### ISSUE TITLE
make two IOCs - with PVI and GUI

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#110]
1. Create an ADSimDetector and ADAravis IOC for bl45p with HDF5 and PVA plugins (At least).
2. To use only auto-generated Support YAML and the Aravis one to use autogenerated IOC yaml (from existing bl45p-iocs builder XML)
3. work with Gary to add PVI and GUI to both

@GDYendell  I should be ready with these for step 3 a by Thurs at current estimates.

**Comment by gilesknap** [comment]
I now have a fully working Aravis IOC running in K8S on bl45p with all the new changes to structure and schema in place.
It came out looking OK (this works with the existing edm screens for bl45p)
```yaml
# yaml-language-server: $schema=https://github.com/epics-containers/ioc-adaravis/releases/download/23.9.1/adaravis.ibek.ioc.schema.json

ioc_name: bl45p-ea-ioc-01
description: Sample and overview cameras IOC for BL45P
# TODO update the schema to remove generic_ioc_image - this is handled in helm chart
# 'outside' and is not an ibek thing anymore
generic_ioc_image: ghcr.io/epics-containers/ioc-adaravis-linux-runtime:23.9.1

entities:
  - type: epics.EpicsCaMaxArrayBytes
    max_bytes: 6000000

  - type: ADAravis.aravisCamera
    CLASS: AVT_Mako_G234B
    PORT: DET.DET
    P: BL45P-EA-MAP-01
    R: ":DET:"
    ID: 172.23.59.11
    PV_ALIAS: "0" # TODO this ARG should have default

  - type: ADCore.NDPvaPlugin
    PORT: DET.PVA
    PVNAME: BL45P-EA-MAP-01:PVA:OUTPUT
    P: BL45P-EA-MAP-01
    R: ":PVA:"
    NDARRAY_PORT: DET.DET
    BLOCK: 1 # TODO remaining ARGS should have defaults
    PRIORITY: 0
    STACKSIZE: 0
    NDARRAY_ADDR: 0

  - type: ADCore.NDFileHDF5
    PORT: DET.HDF5
    P: BL45P-EA-MAP-01
    R: ":HDF5:"
    NDARRAY_PORT: DET.DET
    BLOCK: 1
    NDARRAY_ADDR: 0

  - type: ADAravis.aravisCamera
    CLASS: AVT_Mako_G234B
    PORT: DIFF.DET
    P: BL45P-EA-DIFF-01
    R: ":DET:"
    ID: 172.23.59.12
    PV_ALIAS: "0"
  - type: ADCore.NDPvaPlugin
    PORT: DIFF.PVA
    PVNAME: BL45P-EA-DIFF-01:PVA:OUTPUT
    P: BL45P-EA-DIFF-01
    R: ":PVA:"
    NDARRAY_PORT: DIFF.DET
    BLOCK: 1
    PRIORITY: 0
    STACKSIZE: 0
    NDARRAY_ADDR: 0

  - type: ADCore.NDFileHDF5
    PORT: DIFF.HDF5
    P: BL45P-EA-DIFF-01
    R: ":HDF5:"
    NDARRAY_PORT: DIFF.DET
    BLOCK: 1
    NDARRAY_ADDR: 0
```
