### ISSUE TITLE
Change schema of post_init, pre_init

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#126]
Currently we have:

```yaml
    pre_init:
      - type: text
        value: |
          # simDetectorConfig(portName, maxSizeX, maxSizeY, dataType, maxBuffers, maxMemory)
          simDetectorConfig("{{PORT}}", {{WIDTH}}, {{HEIGHT}}, {{DATATYPE}}, {{BUFFERS}}, {{MEMORY}})
      - type: comment: 
        value: I made a comment.
```
or (because text is the default):
```yaml
    pre_init:
      - value: |
          aravisConfig(const char *portName, const char *cameraName, size_t maxMemory, int priority, int stackSize)
          aravisConfig("{{PORT}}", "{{ID}}", {{MEMORY}}, 0, 1)
```

But it should be:
```yaml
    pre_init:
      - text: |
          # simDetectorConfig(portName, maxSizeX, maxSizeY, dataType, maxBuffers, maxMemory)
          simDetectorConfig("{{PORT}}", {{WIDTH}}, {{HEIGHT}}, {{DATATYPE}}, {{BUFFERS}}, {{MEMORY}})
      - comment: |
          this is a comment
```
@coretl I had changed it so that text was default, thinking that was achieving what you asked for but that is not right because `value:` is not a useful description.
