### ISSUE TITLE
Rendering of jinja in definition arguments fails for DB macros

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#174]
e.g.

```yaml
  - type: pmac.dls_pmac_asyn_motor
    Controller: PPMAC1
    DESC: X
    M: :{{ DESC }}
    P: "{{ Controller.P }}"
```

Causes the DB template eloss_autohome_records.template to (part) render like this:
```yaml
# disable motor when homing
record(calcout, "BL01J-MO-PPMAC-01:X:SDIS") {
#  field(INPA, "{{ Controller.P }}:HM:HOMING CP")
}
```

It should be:
```yaml
# disable motor when homing
record(calcout, "BL01J-MO-PPMAC-01:X:SDIS") {
#  field(INPA, "PPMAC1:HM:HOMING CP")
}
```
