### ISSUE TITLE
the following yaml does not generate PVs for motorsim 

### ISSUE THREAD

**Issue by amichelotti** [epics-containers/ibek#199]
Hi try running the ioc with the following ibek descriptions:
```yaml
ioc_name: yag-screens
description: Yag Screens Simulated 

entities:
  
  - type: motorSim.simMotorController
    controllerName: SCN01CTRL
    P: LEL-DIA-SCN
    numAxes: 6
  
  - type: motorSim.simMotorAxis
    controller: SCN01CTRL
    M: "01:MOT01:"
    DESC: "Axis"
    ADDR: 0
    DLLM: -20000
    DHLM: 20000
    home: 20000
    start: 20000
    DIR: Neg

  - type: motorSim.simMotorAxis
    controller: SCN01CTRL
    M: "02:MOT01:"
    ADDR: 1
    DESC: "Axis"
    DLLM: -20000
    DHLM: 20000
    home: 20000
    start: 20000
    DIR: Neg

  - type: motorSim.simMotorAxis
    controller: SCN01CTRL
    M: "03:MOT01:"
    ADDR: 2
    DESC: "Axis"
    DLLM: -20000
    DHLM: 20000
    home: 20000
    start: 20000
    DIR: Neg

  - type: motorSim.simMotorAxis
    controller: SCN01CTRL
    M: "04:MOT01:"
    DESC: "Axis"
    ADDR: 3
    DLLM: -20000
    DHLM: 20000
    home: 20000
    start: 20000
    DIR: Neg

  - type: motorSim.simMotorAxis
    controller: SCN01CTRL
    M: "05:MOT01:"
    DESC: "Axis"
    ADDR: 4
    DLLM: -20000
    DHLM: 20000
    home: 20000
    start: 20000
    DIR: Neg

  - type: motorSim.simMotorAxis
    controller: SCN01CTRL
    M: "06:MOT01:"
    DESC: "Axis"
    ADDR: 5
    DLLM: -20000
    DHLM: 20000
    home: 20000
    start: 20000
    DIR: Neg
  
  - type: ADSimDetector.simDetector
    PORT: SCN01CAM
    P: LEL-DIA-SCN01
    R: ":CAM01:"
  - type: ADSimDetector.simDetector
    PORT: SCN02CAM
    P: LEL-DIA-SCN02
    R: ":CAM01:"
  - type: ADSimDetector.simDetector
    PORT: SCN03CAM
    P: LEL-DIA-SCN03
    R: ":CAM01:"
  - type: ADSimDetector.simDetector
    PORT: SCN04CAM
    P: LEL-DIA-SCN04
    R: ":CAM01:"
  - type: ADSimDetector.simDetector
    PORT: SCN05CAM
    P: LEL-DIA-SCN05
    R: ":CAM01:"
  - type: ADSimDetector.simDetector
    PORT: SCN06CAM
    P: LEL-DIA-SCN06
    R: ":CAM01:"
```

Motors PV are not created (just cams). If I comment cams the PV are partially created. 
Where am I wrong?
