### ISSUE TITLE
Screen ideas

### ISSUE THREAD

**Issue by thomascobb** [epics-containers/ibek#23]
`motor.screens.yaml` would contain

```yaml
screens:
- name: pmac.DlsPmacAsynMotor
  screen: motor.bob
  macros:
  - motor: $(P)$(M)
```
