### ISSUE TITLE
Add repeats to entity declarations in ioc.yaml

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#258]
This is to allow repeating elements in ioc.yaml.

(details to be reviewd)

Add a new field `repeat` of type list to `entity` that allows you to iterate over a list and instantiate a number of the same entity. The context for each step will include the variables `val` and `idx` which can be used to differentiate the individual entities. 

examples:

```yaml
  - type: ADCore.NDPvaPlugin
    repeat: {{ range(5) | list }} 
    NDARRAY_PORT: DET.CAM
    P: BL47P-EA-DET-01
    PORT: DET.PVA{{ repeate.val }}
    R: ":TX{{ repeat.val }}:"
    PVNAME: BL47P-EA-DET-01:TX{ repeat.val }}:PVA
```

```yaml
  - type: epics.dbpf
    repeat: [ hello, world ]
    pv: BL47P-EA-DET-01:WORD{{ repeat.num }}
    value: "{{ repeat.val }}"
```

**Comment by gilesknap** [comment]
And combining this with #257 we could do

ioc.yaml
```yaml
  - type: epics.dbpf
    repeat: {{ words | list }}
    pv: {{ prefix }}:WORD{{ num }}
    value: "{{ val }}"
```

env.yaml
```
words: [ now, is, the, time, for, all, good ]
prefix: BL47P-EA-DET-01
```

**Comment by gilesknap** [comment]
use of `val` and `num` are a little arbitrary - we could have overrides for these if that seems necessary

**Comment by coretl** [comment]
I like the concept, but rather than a reserved argument I wonder if it would be clearer to make a nested object:
```yaml
  - type: ibek.repeat
    variable: index
    values: {{ range(5) | list }}
    entity:
      type: ADCore.NDPvaPlugin
      NDARRAY_PORT: DET.CAM
      P: BL47P-EA-DET-01
      PORT: DET.PVA{{ index }}
      R: ":TX{{ index }}:"
      PVNAME: BL47P-EA-DET-01:TX{{ index }}:PVA
```
