### ISSUE TITLE
References to broken objects are very hard to debug

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#272]
I've just spent a couple of hours debugging my ioc.yaml because ipac.Hy8002 dropped the need for an interrupt vector. I added a test to ibek to show this. See the YAML below - `interrupt_vector: Vec1` is no longer required and causes the `ipac.Hy8002` entity to be invalid. This in turn causes `DLS8515.DLS8515` to have an invalid reference and fail as partially constructed during de-serialisation. This in turn causes `DLS8515.DLS8515channel` to fail to find one of `DLS8515.DLS8515` parameters (cardid) during its render.

The error is reported as:-
```
FAILED tests/test_cli.py::test_dls_8515 - jinja2.exceptions.UndefinedError: 'ibek.entity_factory.DLS8515_DLS8515 object' has no attribute 'cardid'
```

Which is super unhelpful as the actual issue happened 2 levels of indirection ago.

The solution should be to get this exception to cause deserialization to exit and immediately report the key exception. But I have failed to discover how to do that

https://github.com/epics-containers/ibek/blob/948bd1a6d7603cec87e7d19e6dba898d20463f8f/src/ibek/ioc.py#L28-L32

```yaml
ioc_name: "{{  _global.get_env('IOC_NAME') }}"

description: auto-generated by https://github.com/epics-containers/builder2ibek

entities:
  - type: epics.InterruptVectorVME
    name: Vec1

  - type: epics.InterruptVectorVME
    name: Vec

  - type: ipac.Hy8002
    name: BLX4I-VA-IOC-01-Slot4
    interrupt_vector: Vec1
    slot: 4

  - type: DLS8515.DLS8515
    carrier: BLX4I-VA-IOC-01-Slot4
    interrupt_vector: Vec2
    ipslot: 0
    name: BLX4I-VA-IOC-01.Slot4.A

  - type: DLS8515.DLS8515channel
    baud: 57600
    card: BLX4I-VA-IOC-01.Slot4.A
    channel: 0
    data: 7
    flow: N
    name: VCC1.SER
    parity: E
    stop: 2
```
