### ISSUE TITLE
Improve validation and error handling

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#64]
Some improvements suggested in conversation with @coretl 

- in __getattrs__ make a nice error when a non-existent attribute is requested (I am type X with attrs ... but you have asked for Attr Y)
- also remove need to say object.name instead render object as its id
- Provide a validation capability for defs e.g.
```yaml
defs:
  - name: Psc
    args:
      - name: carrier
        type: object
        description: IPAC carrier name

      - name: interrupt_vector
        type: object
        description: Interrupt Vector reserved with epics.InterruptVectorVME, count=3

    validate:
      - assert: interrupt_vector.count == 3
        message: Interrupt_vector must be reserved with epics.InterruptVectorVME, count=3

```
