### ISSUE TITLE
Description field in definitions are not exposed in vscode popups

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#70]

**Comment by gilesknap** [comment]
e.g.
```yaml
defs:
  - name: Hy8002
    description: adds a Hy8002 carrier card to the IOC
    args:
      - type: id
        name: name
        description: "IPAC identifier (suggested: IPAC<slot>)"
```

'adds a Hy8002 carrier card to the IOC' can only be seen by looking in the original definitions file
