### ISSUE TITLE
Poor connection between function arguments and ibek entity arguments

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#72]
Consider this function definition in Hy8401ip.ibek.support.yaml
```yaml
    script:
      - type: function
        name: Hy8401ipConfigure
        header: |
          #   IpSlot 0=A 1=B 2=C 3=D
          #   ClockRate  0=1Hz  1=2Hz  2=5Hz  3=10Hz 4=20Hz 5=50Hz 6=100Hz7=200Hz 8=500Hz 9=1kHz 10=2kHz11=5kHz 12=10kHz 13=20kHz 14=50kHz 15=100kHz
        args:
          CardId: "{{ card_id }}"
          IPACid: $({{ carrier.name }})
          IpSiteNumber: "{{ ip_site_number }}"
          InterruptVector: $({{ vector.name }})
          InterruptEnable: "{{ int_enable | int }}"
          AiType: 0
          ExternalClock: "{{ external_clock | int }}"
          ClockRate: "{{ clock_rate }}"
          Inhibit: "{{ inhibit | int }}"
          SampleCount: 1
          SampleSpacing: 1
          SampleSize: "{{ sample_size }}"
```

With example resulting entry in the st.cmd
```
# Hy8401ipConfigure CardId IPACid IpSiteNumber InterruptVector InterruptEnable AiType ExternalClock ClockRate Inhibit SampleCount SampleSpacing SampleSize
#   IpSlot 0=A 1=B 2=C 3=D
#   ClockRate  0=1Hz  1=2Hz  2=5Hz  3=10Hz 4=20Hz 5=50Hz 6=100Hz7=200Hz 8=500Hz 9=1kHz 10=2kHz11=5kHz 12=10kHz 13=20kHz 14=50kHz 15=100kHz
Hy8401ipConfigure 40 $(IPAC4) 0 $(Vec0) 0 0 0 15 0 1 1 0
```

In script->function->args we have made up UpperCamelCase names for the arguments that don't directly relate to definition arguments in the support.yaml file. There is no description anywhere of the meaning of AiType SampleCount SampleSpacing. IPACid and InterruptVector etc. are also made up names that have no direct description.

Our first user @AlexanderWells-diamond certainly found this confusing. Not sure there is much we can do - but perhaps at least mandate function args names are snake_cases and match their definition arg where appropriate (but this feels repetative).

**Comment by gilesknap** [comment]
@coretl @GDYendell did we discuss this in the review meeting?

This is really a question about how useful the function type arg is I guess. I'd like to nail down how we want function declaration to work before J20 because its fiddly to change. Let me know if you have thoughts - if not I'll leave as is.

**Comment by gilesknap** [comment]
The decision on this was to remove the names and just list the Args to insert in each for each function argument. e.g. below
We COULD go ahead and insert useful comments by calling help in the ioc shell during startup script generation. This is better than duplicating what is already in the IOCs declared interface.

 ```yaml
    script:
      - type: function
        name: Hy8401ipConfigure
        header: |
          #   IpSlot 0=A 1=B 2=C 3=D
          #   ClockRate  0=1Hz  1=2Hz  2=5Hz  3=10Hz 4=20Hz 5=50Hz 6=100Hz7=200Hz 8=500Hz 9=1kHz 10=2kHz11=5kHz 12=10kHz 13=20kHz 14=50kHz 15=100kHz
        args:
          - "{{ card_id }}"
          - $({{ carrier.name }})
          - "{{ ip_site_number }}"
          - $({{ vector.name }})
          - "{{ int_enable | int }}"
          - 0
          - "{{ external_clock | int }}"
          - "{{ clock_rate }}"
          - "{{ inhibit | int }}"
          - 1
          - 1
          - "{{ sample_size }}"
```
