### ISSUE TITLE
ibek sub-modules

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#78]
I'm looking at implementing AreaDetector IOCs in ibek.

We have a DLS thing called gdaPlugins that is a collection of instantantiations of other builder.py objects. It creates a standard set of ROI and STAT plugins for use by GDA based on some prefixes for the PVs and Asyn port names.

We might not really want gdaPlugins for DII but the principle of builder submodules still stands.

@coretl should we implement an equivalent in ibek? e.g.

```yaml
# yaml-language-server: $schema=../_global/ibek.defs.schema.json

module: gdaPlugins

defs:
  - name: plugins
    description: Defines a standard set of AD plugins for interfacing with gda

    args:
      - type: str
        name: PORT_PREFIX
        description: Port Name for plugins

      - type: str
        name: P
        description: The PV prefix

      - type: str
        name: R
        description: The PV suffix

      - type: str
        name: CAM
        description: The camera port name

      - type: int
        name: PLUGINQUEUE
        description: size of Queues for the plugins

    script:
      - Initialise a set of plugins for interfacing with GDA

    ibek-submodules:
      - name: ADCore.NDRoi
        args:
          P: {{ P }}
          R: ":ROI:"
          PORT: {{ PORT_PREFIX }}.roi
          TIMEOUT: 1
          NDARRAY_PORT: {{ CAM }}

etc ...

```

**Comment by coretl** [comment]
I think the idea is valid, but let's defer making it for as long as possible... I'd also like to propose a separate syntax:

```yaml
# yaml-language-server: $schema=../_global/ibek.defs.schema.json

module: gdaPlugins

defs:
  - name: plugins
    description: Defines a standard set of AD plugins for interfacing with gda

    args:
      - type: str
        name: PORT_PREFIX
        description: Port Name for plugins

      - type: str
        name: P
        description: The PV prefix

      - type: str
        name: R
        description: The PV suffix

      - type: str
        name: CAM
        description: The camera port name

      - type: int
        name: PLUGINQUEUE
        description: size of Queues for the plugins

    entities:
      - type: ADCore.NDRoi
        P: {{ P }}
        R: ":ROI:"
        PORT: {{ PORT_PREFIX }}.roi
        TIMEOUT: 1
        NDARRAY_PORT: {{ CAM }}
      - ...
```
Of course this leads to the recursive idea of what the schema is for these entities, we could just leave it free as these things are likely to be pretty rare...

**Comment by coretl** [comment]
But now I write that, it looks like the existing "templated xml" that we have in builder, so we could go that way:

In `gdaPlugins.ioc.yaml`:
```yaml
# yaml-language-server: $schema=../schemas/all.ibek.support.schema.json
args:
  - type: str
    name: PORT_PREFIX
    description: Port Name for plugins

  - type: str
    name: P
    description: The PV prefix

  - type: str
    name: R
    description: The PV suffix

  - type: str
    name: CAM
    description: The camera port name

  - type: int
    name: PLUGINQUEUE
    description: size of Queues for the plugins
entities:
  - type: ADCore.NDRoi
    P: {{ P }}
    R: ":ROI:"
    PORT: {{ PORT_PREFIX }}.roi
    TIMEOUT: 1
    NDARRAY_PORT: {{ CAM }}
  - ...
```
In `adUtil.support.yaml`:
```yaml
# yaml-language-server: $schema=../_global/ibek.defs.schema.json

module: adUtil

defs:
  - name: plugins
    description: Defines a standard set of AD plugins for interfacing with gda
    template: gdaPlugins.ioc.yaml
```
