### ISSUE TITLE
schema change for database section

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#79]
At present we have
```yaml
databases:
      - file: XXX.template
        include_args: [ A, B, D ]
        define_args: |
          C={{ xxx }}
          E={{ yyy }}
```

First, the use of array/multiline string for include/define is inconsistent. 
Second, Ordering of arguments is lost because they are distributed to two places in the YAML.

I propose this approach:

```yaml
databases:
      - file: XXX.template
        args:  A B C={{ xxx }} D E={{ yyy }} 
```

Whitspace is the separator (except inside jinja quotes) so that you can format as needed e.g.

```yaml
databases:
      - file: XXX.template
        args:  |
          A B D
          C={{ xxx }}
          E={{ yyy }} 
```

@coretl @niamhdougan any thoughts?

**Comment by coretl** [comment]
Slight concern that we are recreating YAML parsing inside a string... At the cost of some vertical space we could format as a list:
```yaml
databases:
  - file: XXX.template
    args:
      - A
      - B
      - C={{ xxx }}
      - D
      - E={{ yyy }}
```
or a dict:
```yaml
databases:
  - file: XXX.template
    args:
      A:
      B:
      C: "{{ xxx }}"
      D:
      E: "{{ yyy }}"
```

**Comment by coretl** [comment]
Actually, the inline version of the dict is reasonable:
```yaml
databases:
  - file: XXX.template
    args: { A, B, C: "{{ xxx }}", D, E: "{{ yyy }}" }
```

**Comment by coretl** [comment]
args outputs
```python
{'A': None, 'B': None, 'C': '{{ xxx }}', 'D': None, 'E': '{{ yyy }}'}
```

**Comment by gilesknap** [comment]
I quite like that.

vscode will format it vertically once the length exceeds 80 chars.

So we get no say in what the layout is but that is probably OK.

**Comment by gilesknap** [comment]
@coretl 

Maybe its worth mentioning that this results in the following format for longer lists of args. ALSO the auto generator will always use this form (because ruamel)

```yaml

    databases:
      - file: $(PMAC)/db/geobrickette_motion_stop.template
        args:
          active_DESC:
          mstop_ZNAM:
          active_OSV:
          active_VAR:
          SCAN:
          mstop_ZSV:
          P:
          mstop_R:
          active_ONAM:
          active_ZNAM:
          mstop_DESC:
          mstop_VAR:
          active_R:
          TIMEOUT:
          active_ZSV:
          mstop_ONAM:
          PORT:
          mstop_OSV:\
```

**Comment by gilesknap** [comment]
sorry above not quite true. The above is what ruamel will do. Vscode formatting will do:
```yaml

    databases:
      - file: $(PMAC)/db/pmacVariableReadLED.template
        args:
          {
            ZSV,
            name,
            OSV,
            ZNAM,
            ONAM,
            SPEED,
            LABEL,
            VAR,
            PORT,
            P,
            Q,
          }
```

**Comment by gilesknap** [comment]
OK so the inline idea does not work because { is significant even inside quotes (!!)
![image](https://github.com/epics-containers/ibek/assets/964827/681d6b26-069e-4232-b8a1-51d94f0ced05)

Therefore I propose that we use the long-form:
```yaml
databases:
  - file: XXX.template
    args:
      A:
      B:
      C: "{{ xxx }}"
      D:
      E: "{{ yyy }}"
```

As @coretl  suggested earlier
