### ISSUE TITLE
Change script schema

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#81]
Another schema change proposal:

At present we have:
```yaml
script:
  - type: once
    value: |
      some once only script lines
  - type: function
    name: myFunc
    args:
      ArgOne: "{{ ARGONE }}"
  - ordinary text
  - appears as a list
  - of lines

post_ioc_init:
  - lines of text
  - after iocInit
```

Proposed change for discussion:
```yaml
script:  
  - type: once
    value: |
      some once only script lines
  - type: function
    name: myFunc
    args:
      ArgOne: "{{ ARG_ONE }}"
  - type: text
    value: |
      ordinary text
      appears a single string
  - type: post_ioc_init
    value: | 
      lines of text
      after iocInit
```

I'm not sold on `type: text` - looking for better names for this

**Comment by gilesknap** [comment]
That was wrong - should be:
```yaml
script:  
  - type: function
    once: false
    name: myFunc
    args:
      ArgOne: "{{ ARG_ONE }}"
  - type: script
    once: false
    post_init: false
    value: |
      ordinary text
      appears a single string
```

**Comment by gilesknap** [comment]
Although I don't know of a need for it we could also support `post_init` in the function type.

**Comment by gilesknap** [comment]
@coretl waddayathink?

**Comment by gilesknap** [comment]
After discussion with @coretl and @GDYendell we have:

```yaml
pre_init:  
  - type: function
    when: first / every / last
    name: myFunc
    args:
      HumanReadableFunctionArgumentName: "{{ ARG_ONE }}"
  - type: comment
    when: first / every / last
    value: |
      ordinary text
      appears as a single string 
      which can be multi-line
      # is automatically added for us in the 
post_init:
  AS ABOVE
```

**Comment by gilesknap** [comment]
@GDYendell @coretl 

Gary, you may remember that I was reluctant to remove the ability to add fre-form text to the startup script. I'm now implementing the change as above and have come across an example of where I think fre-form would be tidier.

Let me know what you think:
```yaml
    # TODO: the removal of script and post_ioc_init means we need to
    # explicitly list each of these functions and is rather verbose
    # TODO consider adding a "text" type to pre_init and post_init
    # for this purpose
    pre_init:
      - type: comment
        when: first
        value: |
          One time initialization for all event receivers
      - type: function
        when: first
        name: ErTimeProviderInit
        args:
          priority: "{{ priority }}"
      - type: function
        when: first
        name: installLastResortEventProvider
        args: {}
      - type: function
        when: first
        name: syncSysClock
        args: {}

        # ABOVE USED TO BE LESS VERBOSE
        # script:
        #   value: |
        #     # One time initialization for all event receivers
        #     ErTimeProviderInit {{ priority }}
        #     installLastResortEventProvider
        #     syncSysClock
```

**Comment by coretl** [comment]
How about we merge function and comment and have one thing that does both:
```yaml
    pre_init:
      - when: first       
        comment: One time initialization for all event receivers
        function: ErTimeProviderInit
        args:
          priority: "{{ priority }}"
      - when: first
        function: installLastResortEventProvider
      - when: first
        function: syncSysClock
```

**Comment by coretl** [comment]
Outputs:
```
# One time initialization for all event receivers
# ErTimeProviderInit priority
ErTimeProviderInit 1
installLastResortEventProvider
syncSysClock
```

**Comment by coretl** [comment]
Alternatively:
```yaml
    pre_init:
      - text: |
          # One time initialization for all event receivers
          ErTimeProviderInit {{ priority }}
          installLastResortEventProvider
          syncSysClock
```

**Comment by GDYendell** [comment]
I think allow arbitrary text for edge cases, but use of function should be encouraged for consistent formatting when possible.

**Comment by gilesknap** [comment]
After pydantic conversion I will complete this Issue by implementing Tom's suggestions as follows:

- pre_init, post_init become list of script_entry which can have any combination of 
  - function: function_name
  - comment: comment_text
  - text: raw_text
  - args: list of args as before - errors if function name not supplied
  - when: defaults to every
 
If you supply all of function, comment, text they appear in alphabetical order.

Functions get auto generated comment above first invocation, but not if there are zero arguments

**Comment by gilesknap** [comment]
Do this before J20

**Comment by gilesknap** [comment]
I have a new proposal to simplify this down to just pre_init and post_init text. See https://github.com/epics-containers/ibek/issues/72#issuecomment-1732411567

```yaml
pre_init:
- type: text 
  when: first / last / every
  value: |
  # my comment can go here
  myfunc(1, 2, {{arg}}, 4) 
  more_funcs_as_needed()
pre_init:
  AS ABOVE
```

**Comment by coretl** [comment]
Suggest:
```yaml
pre_init:
- when: first / last / every
  text: |
  # my comment can go here
  myfunc(1, 2, {{arg}}, 4) 
  more_funcs_as_needed()
pre_init:
  AS ABOVE
```
