### ISSUE TITLE
Change ioc.yaml to e.g. bl38p-mo-panda-01.yaml and provide access to the filename prefix Jinja renders.

### ISSUE THREAD

**Issue by GDYendell** [epics-containers/ibek#82]
It would be great to be able to add a `description: ` field to the ioc yaml that would be used to generate a `$(P):DESCRIPTION` PV inside the IOC. This could be used to populate hardware status and for scripts summarising IOCs on a beamline.

**Comment by gilesknap** [comment]
@GDYendell where would $(P) come from? None, or one or more of the templates in the IOC might have a $P.

**Comment by gilesknap** [comment]
Perhaps the prefix could come from $IOC from the deviocstats template.

**Comment by GDYendell** [comment]
Yeah I think it should be the name of the IOC. Will there always be a devIOCStats by default, without the beamline engineer having to define it manually?

**Comment by gilesknap** [comment]
Thats a good question. At present no. But this conversation plus other considerations are making me think that this is a good idea:

- have a yaml entry that specifies the IOC prefix for devIOCstats (or just use the name field that we already have - but this means constraining that field to legal PV prefixes)
- automatically instantiate devIOCstats using that prefix

@coretl do you have any views on this?

**Comment by coretl** [comment]
I have a slight preference for no magic, but also want to avoid copy paste errors. How about:

```yaml
# Contents of BLxxI-MO-IOC-01.ibek.ioc.yaml
generic_ioc: ...
entities:
  - type: devIocStat.iocStats
    P: {{ yaml_prefix }}
    description: All endstation motors
  - type: pmac.pmac
  ...
```

where `yaml_prefix` is passed into the jinja context with value "yaml_filename.basename.split(".")[0]`

If we do this then we need the top level `ioc_name` and `description` for anything?

**Comment by gilesknap** [comment]
Just want to say: We need this.

At present I'm writing the name of the IOC in three places:

1. the folder name of the IOC
2. twice in the YAML
```yaml
# yaml-language-server: $schema=https://github.com/epics-containers/ioc-pmac/releases/download/2023.11.1/ibek.ioc.schema.json

ioc_name: bl20j-mo-brick-01
description: geobrick 01

entities:
  - type: devIocStats.iocAdminSoft
    IOC: bl20j-mo-brick-01
```

**Comment by coretl** [comment]
At the moment we seem to have both lowercase and uppercase versions of the EPICS prefix. Can we standardise on the uppercase version? (as devIocStats will require the uppercase to make the right PVs).

How about we have `BLxxI-MO-BRICK-01/ioc.yaml` which uses `{{ yaml_dir_name }}` whenever it needs the string `BLxxI-MO-BRICK-01`?

**Comment by gilesknap** [comment]
@coretl

I disallow uppercase names because helm will not accept them.
https://epics-containers.github.io/main/user/tutorials/create_beamline.html#create-a-beamline-repository
https://helm.sh/docs/chart_best_practices/conventions/#chart-names

I also disallow them because they are a pain in the arse to type and because they look like they come from the 80's computer era and are an offence to cloud native tools. :-)

I think I'm OK with PV names are always ucase and kubernetes names are always lcase. If we have that as a rule then we can translate where required.

**Comment by gilesknap** [comment]
So I like your proposal but we need 
`{{ yaml_dir_name_upper }}` and  `{{ yaml_dir_name_lower }}`

**Comment by gilesknap** [comment]
@coretl if you like this I'll do it next because it's quick but invasive.

**Comment by coretl** [comment]
I propose using https://jinja.palletsprojects.com/en/2.11.x/templates/#upper, so it would be `{{ yaml_dir_name | upper }}`. It looks like helm can do the same thing https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#pipelines. If helm has a different name to `yaml_dir_name` then we should use that instead...

**Comment by gilesknap** [comment]
Ah.

At all times that the ioc.yaml is being rendered it has been symlinked or copied into a generic folder name. This is particularly true at runtime where ioc.yaml is an entry in a config map and its path is just /epics/ioc/config/ioc.yaml.

So we could contrive to pass the folder name around to all the right places OR we could make `ioc_name: ` in the root of `ioc.yaml` the source of truth.

This does still mean repetition of the name in folder name and file header. Although the folder name does not have to be the same anymore it still makes sense to have them match. And that rather grates on me as its fiddly to maintain and could easily confuse.

more thought required ...

**Comment by gilesknap** [comment]
After a discussion with @coretl we decided the best course of action is to have named files. e.g. ioc.yaml --> bl38p-mo-panda-01.yaml and use `{{ yaml_ioc_filename | upper }}` for iocStats IOC field.

However this is a breaking change. We also decided to collect all breaking changes up for a single sprint in a few months time after multiple people have tried out epics-containers. Hence https://github.com/orgs/epics-containers/projects/1

**Comment by gilesknap** [comment]
I have updated ibek to support the named ioc.yaml file in future here 52233540d65.

The approach is to have two additional global names in the Jinja context.

- ioc_yaml_file_name
- ioc_name

`ioc_name` is rendered at the beginning of `ibek runtime` commands so that it may also include `ioc_yaml_file_name`.  In turn  `ioc_yaml_file_name` holds the stem of the yaml file name.

This means you can write an instance like this:

```yaml
# yaml-language-server: $schema=https://github.com/epics-containers/ioc-adaravis/releases/download/2023.11.2/ibek.ioc.schema.json

ioc_name: "{{ ioc_yaml_file_name }}"
description: camera for diagnostic 2

entities:
  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"
```

This would give you `IOC` for you iocStatus prefix at present because every ioc instance has `ioc.yaml` filename but you can instead just write:

```yaml
ioc_name: bl16i-mo-ioc-12
...
```

In this way we can for now have fixed names in `ioc_name` for now and then replace with {{ ioc_yaml_file_name }} once we change the filenames from ioc.yaml.

I then propose leaving the ibek code as is because it gives the ability to tweak your IOC name with suffixes or not use the filename at all if you want for some reason. 

The alternative is we ditch ioc_name altogether an use ioc_yaml_file_name directly in the entity args. I slightly prefer the former as it gives you one place to supply a modified ioc_name and then re-use it multiple times. 

@coretl does that sound OK?

**Comment by gilesknap** [comment]
While we are doing this we may as well change the name of the binary to the ioc name too. At present the binary is 'ioc'.

I just realized that all iocs look the same when running top on a server (although I was only doing this due to a hybrid server - in theory we should not care when everything is wrapped in pods and we only use K8S monitoring tools)

**Comment by gilesknap** [comment]
https://github.com/epics-containers/ibek/pull/147 has partially implemented this fix.

Completing the issue still requires:

updating ec to handle any stem for ioc.yaml
updating the tutorials to encourage unique naming of the ioc yaml
making sure that liveness.sh is pickiing up the same stem name (somehow - this uses helm chart name at present)

**Comment by coretl** [comment]
> making sure that liveness.sh is pickiing up the same stem name (somehow - this uses helm chart name at present)

How about we add a new section to `devIocStats.ibek.support.yaml`:
```yaml
- pre_init: ...
- liveness:
  - type: pv_connected
    pv: {{ IOC }}:UPTIME
```

Then we make the standard liveness.sh check all the PVs listed in instances of that YAML file. We can then do things like check the "Camserver disconnected: reboot IOC" source PV for Pilatus and automatically reboot the IOC in that state...
